# Generated by Django 4.2.9 on 2024-02-03 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="fine_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkout",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="prefix",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="due_date",
            field=models.DateField(default=datetime.date(2024, 2, 10)),
        ),
    ]
