# Generated by Django 4.2.9 on 2024-01-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='prefix',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
