# Generated by Django 4.2.9 on 2024-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_checkout_fine_amount_checkout_is_returned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="prefix",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
